services:
  app:
    build: .
    image: patterns-gof/node:16.16-alpine
    container_name: patterns-gof-app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/app
    ports:
      - 3333:3333